### ISSUE TITLE
How's the progress going on bruv ?

### ISSUE THREAD

**Issue by RayyanNafees** [rafalp/trpc-core#10]

**Comment by rafalp** [comment]
I am experimenting with this library because I am looking for new API solution for [Misago](https://github.com/rafalp/Misago/) which currently uses Django REST framework. I'll return to this when I finish other work I've planned for it. That may happen sometime late this year, or early in 2024.

But there's no guarantee I won't drop TRPC all together and create custom simple RPC library that takes inspiration from it and my GraphQL experience.
